---
resources:
- name: BigQueryPublisher
  type: git
  source:
    uri: https://github.com/selfhydro/BigQueryPublisher.git

jobs:
- name: unit
  plan:
  - get: BigQueryPublisher
    trigger: true
  - task: unit
    file: BigQueryPublisher/.ci/test.yml

- name: deploy
  plan:
    - get: BigQueryPublisher
      trigger: true
      passed: [unit]
    - task: deploy
      file: BigQueryPublisher/.ci/deploy.yml
